spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///coupon
    password: 994397
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
mybatis:
  mapper-locations: classpath*:mapper/*.xml
hbase:
  config:
    hbase.zookeeper.quorum: 127.0.0.1
    hbase.zookeeper.port: 2181
    hbase.zookeeper.znode: /hbase
    hbase.client.keyvalue.maxsize: 1572864000


