package com.github.coupon.dao;

import com.github.coupon.entity.UserCoupon;
import com.github.coupon.entity.UserCouponExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface UserCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    long countByExample(UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    int deleteByExample(UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    int insert(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    int insertSelective(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    List<UserCoupon> selectByExampleWithRowbounds(UserCouponExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    List<UserCoupon> selectByExample(UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    UserCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserCoupon record, @Param("example") UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    int updateByExample(@Param("record") UserCoupon record, @Param("example") UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    int updateByPrimaryKeySelective(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    int updateByPrimaryKey(UserCoupon record);

    int insertBatch(List<UserCoupon> list);
}