package com.github.coupon.dao;

import com.github.coupon.entity.SendCouponTask;
import com.github.coupon.entity.SendCouponTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SendCouponTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_coupon_task
     *
     * @mbg.generated Tue Jun 11 01:43:43 CST 2019
     */
    long countByExample(SendCouponTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_coupon_task
     *
     * @mbg.generated Tue Jun 11 01:43:43 CST 2019
     */
    int deleteByExample(SendCouponTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_coupon_task
     *
     * @mbg.generated Tue Jun 11 01:43:43 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_coupon_task
     *
     * @mbg.generated Tue Jun 11 01:43:43 CST 2019
     */
    int insert(SendCouponTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_coupon_task
     *
     * @mbg.generated Tue Jun 11 01:43:43 CST 2019
     */
    int insertSelective(SendCouponTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_coupon_task
     *
     * @mbg.generated Tue Jun 11 01:43:43 CST 2019
     */
    List<SendCouponTask> selectByExampleWithRowbounds(SendCouponTaskExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_coupon_task
     *
     * @mbg.generated Tue Jun 11 01:43:43 CST 2019
     */
    List<SendCouponTask> selectByExample(SendCouponTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_coupon_task
     *
     * @mbg.generated Tue Jun 11 01:43:43 CST 2019
     */
    SendCouponTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_coupon_task
     *
     * @mbg.generated Tue Jun 11 01:43:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SendCouponTask record, @Param("example") SendCouponTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_coupon_task
     *
     * @mbg.generated Tue Jun 11 01:43:43 CST 2019
     */
    int updateByExample(@Param("record") SendCouponTask record, @Param("example") SendCouponTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_coupon_task
     *
     * @mbg.generated Tue Jun 11 01:43:43 CST 2019
     */
    int updateByPrimaryKeySelective(SendCouponTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_coupon_task
     *
     * @mbg.generated Tue Jun 11 01:43:43 CST 2019
     */
    int updateByPrimaryKey(SendCouponTask record);
}