package com.github.coupon.entity;

import java.io.Serializable;
import java.util.Date;

public class Coupon implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.id
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.name
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.type
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.use_type
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    private String useType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.is_enable
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    private String isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.val
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    private String val;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.create_date
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.id
     *
     * @return the value of coupon.id
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.id
     *
     * @param id the value for coupon.id
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.name
     *
     * @return the value of coupon.name
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.name
     *
     * @param name the value for coupon.name
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.type
     *
     * @return the value of coupon.type
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.type
     *
     * @param type the value for coupon.type
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.use_type
     *
     * @return the value of coupon.use_type
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    public String getUseType() {
        return useType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.use_type
     *
     * @param useType the value for coupon.use_type
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    public void setUseType(String useType) {
        this.useType = useType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.is_enable
     *
     * @return the value of coupon.is_enable
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.is_enable
     *
     * @param isEnable the value for coupon.is_enable
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.val
     *
     * @return the value of coupon.val
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    public String getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.val
     *
     * @param val the value for coupon.val
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    public void setVal(String val) {
        this.val = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.create_date
     *
     * @return the value of coupon.create_date
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.create_date
     *
     * @param createDate the value for coupon.create_date
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated Mon Jun 10 23:16:08 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", useType=").append(useType);
        sb.append(", isEnable=").append(isEnable);
        sb.append(", val=").append(val);
        sb.append(", createDate=").append(createDate);
        sb.append("]");
        return sb.toString();
    }
}