package com.github.coupon.entity;

import java.io.Serializable;
import java.util.Date;

public class SendCoupon implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_coupon.id
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_coupon.coupon_id
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    private Integer couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_coupon.vip_ids
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    private String vipIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_coupon.count
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_coupon.state
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_coupon.create_date
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table send_coupon
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_coupon.id
     *
     * @return the value of send_coupon.id
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_coupon.id
     *
     * @param id the value for send_coupon.id
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_coupon.coupon_id
     *
     * @return the value of send_coupon.coupon_id
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_coupon.coupon_id
     *
     * @param couponId the value for send_coupon.coupon_id
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_coupon.vip_ids
     *
     * @return the value of send_coupon.vip_ids
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    public String getVipIds() {
        return vipIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_coupon.vip_ids
     *
     * @param vipIds the value for send_coupon.vip_ids
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    public void setVipIds(String vipIds) {
        this.vipIds = vipIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_coupon.count
     *
     * @return the value of send_coupon.count
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_coupon.count
     *
     * @param count the value for send_coupon.count
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_coupon.state
     *
     * @return the value of send_coupon.state
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_coupon.state
     *
     * @param state the value for send_coupon.state
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_coupon.create_date
     *
     * @return the value of send_coupon.create_date
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_coupon.create_date
     *
     * @param createDate the value for send_coupon.create_date
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_coupon
     *
     * @mbg.generated Mon Jun 10 23:15:29 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", couponId=").append(couponId);
        sb.append(", vipIds=").append(vipIds);
        sb.append(", count=").append(count);
        sb.append(", state=").append(state);
        sb.append(", createDate=").append(createDate);
        sb.append("]");
        return sb.toString();
    }
}