package com.github.coupon.entity;

import java.io.Serializable;
import java.util.Date;

public class UserCoupon implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coupon.id
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coupon.is_active
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    private String isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coupon.coupon_id
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    private Integer couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coupon.user_id
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coupon.is_use
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    private String isUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coupon.use_date
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    private Date useDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coupon.is_lock
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    private String isLock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_coupon.create_date
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_coupon
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coupon.id
     *
     * @return the value of user_coupon.id
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coupon.id
     *
     * @param id the value for user_coupon.id
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coupon.is_active
     *
     * @return the value of user_coupon.is_active
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coupon.is_active
     *
     * @param isActive the value for user_coupon.is_active
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coupon.coupon_id
     *
     * @return the value of user_coupon.coupon_id
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coupon.coupon_id
     *
     * @param couponId the value for user_coupon.coupon_id
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coupon.user_id
     *
     * @return the value of user_coupon.user_id
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coupon.user_id
     *
     * @param userId the value for user_coupon.user_id
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coupon.is_use
     *
     * @return the value of user_coupon.is_use
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    public String getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coupon.is_use
     *
     * @param isUse the value for user_coupon.is_use
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    public void setIsUse(String isUse) {
        this.isUse = isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coupon.use_date
     *
     * @return the value of user_coupon.use_date
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    public Date getUseDate() {
        return useDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coupon.use_date
     *
     * @param useDate the value for user_coupon.use_date
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    public void setUseDate(Date useDate) {
        this.useDate = useDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coupon.is_lock
     *
     * @return the value of user_coupon.is_lock
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    public String getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coupon.is_lock
     *
     * @param isLock the value for user_coupon.is_lock
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    public void setIsLock(String isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coupon.create_date
     *
     * @return the value of user_coupon.create_date
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coupon.create_date
     *
     * @param createDate the value for user_coupon.create_date
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated Mon Jun 10 23:16:28 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isActive=").append(isActive);
        sb.append(", couponId=").append(couponId);
        sb.append(", userId=").append(userId);
        sb.append(", isUse=").append(isUse);
        sb.append(", useDate=").append(useDate);
        sb.append(", isLock=").append(isLock);
        sb.append(", createDate=").append(createDate);
        sb.append("]");
        return sb.toString();
    }
}